import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Toaster } from "react-hot-toast"

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
    title: "Google Classroom",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode,
    params: {
        locale: string
    }
}
export default function LocaleLayout({
    children, params: { locale }
}: RootLayoutProps) {
    return (
        <html >
            <body className={poppins.className}>{children}
                <ModalProvider />
                <Toaster position="top-right"
                    reverseOrder={false} />
            </body>
        </html>
    );
}
